# For more information: https://laravel.com/docs/sail
version: '3'
services:
  db:
    image: mysql:5.7
    container_name: parsing_mysql
    environment:
      MYSQL_DATABASE: parsing
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  php:
    image: webdevops/php:7.4
    container_name: parsing_php
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 5000M
      PHP_POST_MAX_SIZE: 5000M
    volumes:
      - "./:/laravel"
    working_dir: '/laravel'
  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    container_name: parsing_nginx
    environment:
      WEB_DOCUMENT_ROOT: /laravel/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/laravel"
    ports:
      - "80:80"
